config/routes.rb
Rails.application.routes.draw do

  root 'books#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
    resources :users, only: [:show] do
      resources :notifications, only: [:create, :update]
    end
  end

  resources :libraries
  resources :copies, only: [:create, :update, :edit]

  resources :books do
    resources :borrows, only: [:create, :update]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  require "csv"

  validates :title, :pages, presence: true

  has_many :notifications
  has_many :borrows
  has_many :users, through: :borrows, source: :user
  has_many :libraries, through: :borrows, source: :library
  has_many :copies
  has_many :libraries, through: :copies, source: :library

  def self.search(search)
    if search
      where(["title ILIKE ?","%#{search}%"])
    else
      all
    end
  end

end

app/models/borrow.rb
class Borrow < ApplicationRecord

  belongs_to :user
  belongs_to :book
  belongs_to :library

  scope :on_loan, -> { where(borrow_status: "on_loan") }
  scope :returns, -> { where(borrow_status: "returned") }

  def self.book_available?(book, library)
    copies = Borrow.copies_available(book, library)
    on_loan = Borrow.on_loan_count(book, library)
    copies - on_loan >= 1
  end

  def self.on_loan_count(book, library)
    Borrow.where("library_id = ?", library.id).where("book_id = ?", book.id).on_loan.count
  end

  def self.copies_available(book, library)
    Copy.where("library_id = ?", library.id).where("book_id = ?", book.id).first.copies
  end



end

app/models/copy.rb
class Copy < ApplicationRecord

  belongs_to :book
  belongs_to :library

  def self.copies_access(book, libraries)
    copies = []
    libraries.each do |library|
      copy = Copy.where("library_id = ?", library.id).where("book_id = ?", book.id).first
      copies << copy
    end
    return copies
  end

end

app/models/library.rb
class Library < ApplicationRecord

  has_many :borrows
  has_many :copies
  has_many :notifications
  has_many :books, through: :borrows, source: :book
  has_many :books, through: :copies, source: :book

end

app/models/notification.rb
class Notification < ApplicationRecord

  belongs_to :book
  belongs_to :library
  belongs_to :user

  scope :unsent_notifications, -> { where(notified: false) }

  def self.notification_mailer(notifications)
    notifications.each do |notification|
      NotificationMailer.book_available_email(notification).deliver
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



  validates :email, :first_name, :last_name, presence: true

  has_many :notifications
  has_many :borrows
  has_many :books, through: :borrows, source: :book


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def require_login
    unless current_user
      flash[:alert] = "You must be logged in to see this person's contact information!"
      redirect_to login_path
    end
  end

  helper_method :current_user
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :is_admin?, only: [:new, :edit, :update]

  def index
    @libraries = Library.all
    @books = Book.search(params[:search])
  end

  def show
    @book = Book.find(params[:id])
    @on_loan = @book.borrows.on_loan
    @returns = @book.borrows.returns
    @libraries = @book.libraries

  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_url, notice: "Book created!"
    else
      flash.now[:alert] = @book.errors.full_messages
      render "new"
    end
  end

  def edit
    @book = Book.find(params[:id])
    @libraries = @book.libraries
    @copies = Copy.copies_access(@book, @libraries)
  end

  def update
    @book = Book.find(params[:id])
    @libraries = @book.libraries
    @copies = Copy.copies_access(@book, @libraries)

    if @book.update_attributes(book_params)
      redirect_to books_url(@book)
    else
      render "edit"
    end
  end

  def is_admin?
    if current_user.admin != true
      redirect_to books_url, notice: "You do not have permissions to do that!"
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :genre, :subgenre, :pages, :publisher)
  end

end

app/controllers/borrows_controller.rb
class BorrowsController < ApplicationController
  before_action :authenticate_user!


  def create
    @borrow = Borrow.new
    @borrow.due_date = Time.now + 1.week
    @borrow.user = current_user
    @book = Book.find(params[:book_id])
    @borrow.book = @book
    @library = Library.find(params[:library_id])
    @borrow.library = @library
    # checks to see if all are loaned
    if Borrow.book_available?(@book, @library)
      @borrow.save
      redirect_to user_url(current_user), notice: "Book added!"
    else
      redirect_to request.referrer, notice: "All copies have been loaned, please check back later!"
    end
  end

  def update
    # Nested route gives a book id for the params, need to figure out how to get params to list borrow_id instead
    # Probably an association problem
    @borrow = Borrow.find(params[:book_id])
    @borrow.update(borrow_status: "returned")
    @borrow.update(date_returned: Time.now)

    @notifications = @borrow.book.notifications.unsent_notifications
    Notification.notification_mailer(@notifications)
    redirect_to user_url(current_user), notice: "Book Returned!"
  end

end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController

  def show
    @library = Library.find(params[:id])
    @books = @library.books
  end

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  before_action :authenticate_user!

  def create
    @notification = Notification.new
    @notification.user = current_user
    @book = Book.find(params[:book_id])
    @notification.book = @book
    @library = Library.find(params[:library_id])
    @notification.library = @library
    # checks to see if all are loaned
    if @notification.save
      redirect_to user_url(current_user), notice: "Notification Added!"
    end
  end

  def update
    # Nested route gives a user id for the params, need to figure out how to get params to list notification_id instead
    @notification = Notification.find(params[:user_id])
    @notification.update(:notified => true)
    # check for notifications
    redirect_to user_url(current_user), notice: "Notification deleted!"
  end

  # def destroy
  #   @notification = Notification.find(params[:notification_id])
  #   if @notification.destroy
  #     redirect_to user_url(current_user), notice: "Notification deleted!"
  #   end
  # end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
   params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
   params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController

  def show
    @user = User.find(params[:id])
    @on_loan = @user.borrows.on_loan
    @returned = @user.borrows.returns
    @notifications = @user.notifications.unsent_notifications
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/borrows_helper.rb
module BorrowsHelper
end

app/helpers/copies_helper.rb
module CopiesHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book_form.html.erb
<%= form_for book, :html=> { class: 'form-group' } do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :author%>
    <%= f.text_field :author, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :publisher %>
    <%= f.text_area :publisher, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :genre %>
    <%= f.text_area :genre, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :subgenre %>
    <%= f.text_area :subgenre, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :pages %>
    <%= f.number_field :pages, :class => "form-control" %>
  </div>

    <div class="form-group">
      <% @copies.each do |copy| %>
        <%= f.fields_for copy do |ff|%>
          <%= ff.label :name, "#{copy.library.library_name} Copies" %>
          <%= ff.number_field :copies %>
        <% end %>
      <% end %>
    </div>

  <%= f.submit 'Submit', :class => "btn btn-primary" %>

<% end %>

app/views/books/edit.html.erb
<h2>Edit Details</h2>

<%= form_for @book, :html=> { class: 'form-group' } do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :author%>
    <%= f.text_field :author, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :publisher %>
    <%= f.text_area :publisher, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :genre %>
    <%= f.text_area :genre, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :subgenre %>
    <%= f.text_area :subgenre, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :pages %>
    <%= f.number_field :pages, :class => "form-control" %>
  </div>

    <div class="form-group">
      <% @copies.each do |copy| %>
        <%= f.fields_for copy do |ff|%>
          <%= ff.label :name, "#{copy.library.library_name} Copies" %>
          <%= ff.number_field :copies %>
        <% end %>
      <% end %>
    </div>

  <%= f.submit 'Submit', :class => "btn btn-primary" %>

<% end %>

app/views/books/index.html.erb
<h2>Libraries Index</h2>

<ul class="list-group">
  <% @libraries.each do |library| %>
    <li class="list-group-item tab-pane"><%= link_to library.library_name, library_path(library), :class => "" %></li>
  <% end %>
</ul>


<h2>Books Index</h2>

<ul class="list-group">
  <% @books.each do |book| %>
    <li class="list-group-item tab-pane"><%= link_to book.title, book_path(book), :class => "" %></li>
  <% end %>
</ul>

app/views/books/new.html.erb
<h2>Add A New Book</h2>

<%= form_for @book, :html=> { class: 'form-group' } do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :author%>
    <%= f.text_field :author, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :publisher %>
    <%= f.text_area :publisher, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :genre %>
    <%= f.text_area :genre, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :subgenre %>
    <%= f.text_area :subgenre, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :pages %>
    <%= f.number_field :pages, :class => "form-control" %>
  </div>

  <%= f.submit 'Submit', :class => "btn btn-primary" %>

<% end %>

app/views/books/show.html.erb
<h2>Details for: <%= @book.title %></h2>

<ul class="list-group">
  <li class="list-group-item">Author: <%= @book.author %></li>

  <li class="list-group-item">Publisher: <%= @book.publisher %></li>

  <li class="list-group-item">Genre: <%= @book.genre %></li>

  <li class="list-group-item">Sub-genre: <%= @book.subgenre %></li>

  <li class="list-group-item">Number of pages: <%= @book.pages %></li>

</ul>

<h2>Branches Available</h2>

<ul class="list-group">
  <% @libraries.each do |library| %>
    <li class="list-group-item"><%= link_to library.library_name, library_path(library) %>
    <% if user_signed_in? && Borrow.book_available?(@book, library) %>
      <%= link_to "Borrow Me!", book_borrows_path(@book, :library_id => library), method: :create, :class => "btn btn-primary" %>
    <% elsif user_signed_in? && Borrow.book_available?(@book, library) == false %>
      <%= link_to "Notify Me When This is Available", user_notifications_path(current_user, :library_id => library, :book_id => @book), method: :create, :class => "btn btn-primary" %>
    <% end %>
      <h6>Copies Left: <%= Borrow.copies_available(@book, library) - Borrow.on_loan_count(@book, library) %><h4></li>
  <% end %>
</ul>

<% if user_signed_in? && current_user.admin == true %>
  <%= link_to "Edit Book Details", edit_book_path(@book), :class => "btn btn-primary" %>
<% end %>

app/views/libraries/show.html.erb
<h2><%= @library.library_name %></h2>
<ul class="list-group">
  <li class="list-group-item">Address: <%= @library.address %></li>
  <li class="list-group-item">Phone: <%= @library.phone_number %></li>
</ul>

<h2>Books Index</h2>
<ul class="list-group">
  <% @books.each do |book| %>
    <li class="list-group-item tab-pane"><%= link_to book.title, book_path(book), :class => "" %></li>
  <% end %>
</ul>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <p>
    <%= user.first_name %>
    <%= user.last_name %>
  </p>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>

  <h2>Register</h2>

  <%= f.text_field :first_name, placeholder: "First Name" %>

  <%= f.text_field :last_name, placeholder: "Last Name" %>

  <%= f.text_field :email, placeholder: "Email" %>

  <%= f.password_field :password, placeholder: "Password" %>

  <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>

  <%= f.submit 'Sign Up', class: 'btn' %>

<% end %>

app/views/users/show.html.erb
<h2>Hi <%= @user.first_name %>! This is your profile</h2>

<h3>Currently On Loan</h3>

<ul class="list-group">
  <% @on_loan.each do |borrow| %>
    <li class="list-group-item"><%= borrow.book.title %> | Due: <%= borrow.due_date.strftime("%A, %B %d") %> | Branch: <%= borrow.library.library_name %> | <%= link_to "Return", book_borrow_path(borrow), method: :patch, :class => "btn-sm btn-primary" %></li>
  <% end %>
</ul>

<h3>Watching</h3>

<ul class="list-group">
  <% @notifications.each do |notification| %>
    <li class="list-group-item"><%= notification.book.title %> | Branch: <%= notification.library.library_name %> | <%= link_to "Remove Notification", user_notification_path(notification), method: :patch, :class => "btn-sm btn-primary" %></li>
  <% end %>
</ul>

<h3>History</h3>

<ul class="list-group">
  <% @returned.each do |borrow| %>
    <li class="list-group-item"><%= borrow.book.title %>
    (Returned: <%= borrow .date_returned.strftime("%A, %B %d") %> at <%= borrow.library.library_name %> )</li>
  <% end %>
</ul>