config/routes.rb
Rails.application.routes.draw do

  root 'books#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
    resources :users, only: [:show] do
      resources :notifications, only: [:create, :update]
    end
  end

  resources :libraries
  resources :copies, only: [:create, :update, :edit]

  resources :books do
    resources :borrows, only: [:create, :update]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  require "csv"

  validates :title, :pages, presence: true

  has_many :notifications
  has_many :borrows
  has_many :users, through: :borrows, source: :user
  has_many :libraries, through: :borrows, source: :library
  has_many :copies
  has_many :libraries, through: :copies, source: :library

  def self.search(search)
    if search
      where(["title ILIKE ?","%#{search}%"])
    else
      all
    end
  end

end

app/models/borrow.rb
class Borrow < ApplicationRecord

  belongs_to :user
  belongs_to :book
  belongs_to :library

  scope :on_loan, -> { where(borrow_status: "on_loan") }
  scope :returns, -> { where(borrow_status: "returned") }

  def self.book_available?(book, library)
    copies = Borrow.copies_available(book, library)
    on_loan = Borrow.on_loan_count(book, library)
    copies - on_loan >= 1
  end

  def self.on_loan_count(book, library)
    Borrow.where("library_id = ?", library.id).where("book_id = ?", book.id).on_loan.count
  end

  def self.copies_available(book, library)
    Copy.where("library_id = ?", library.id).where("book_id = ?", book.id).first.copies
  end



end

app/models/copy.rb
class Copy < ApplicationRecord

  belongs_to :book
  belongs_to :library

  def self.copies_access(book, libraries)
    copies = []
    libraries.each do |library|
      copy = Copy.where("library_id = ?", library.id).where("book_id = ?", book.id).first
      copies << copy
    end
    return copies
  end

end

app/models/library.rb
class Library < ApplicationRecord

  has_many :borrows
  has_many :copies
  has_many :notifications
  has_many :books, through: :borrows, source: :book
  has_many :books, through: :copies, source: :book

end

app/models/notification.rb
class Notification < ApplicationRecord

  belongs_to :book
  belongs_to :library
  belongs_to :user

  scope :unsent_notifications, -> { where(notified: false) }

  def self.notification_mailer(notifications)
    notifications.each do |notification|
      NotificationMailer.book_available_email(notification).deliver
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



  validates :email, :first_name, :last_name, presence: true

  has_many :notifications
  has_many :borrows
  has_many :books, through: :borrows, source: :book


end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :is_admin?, only: [:new, :edit, :update]

  def index
    @libraries = Library.all
    @books = Book.search(params[:search])
  end

  def show
    @book = Book.find(params[:id])
    @on_loan = @book.borrows.on_loan
    @returns = @book.borrows.returns
    @libraries = @book.libraries

  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_url, notice: "Book created!"
    else
      flash.now[:alert] = @book.errors.full_messages
      render "new"
    end
  end

  def edit
    @book = Book.find(params[:id])
    @libraries = @book.libraries
    @copies = Copy.copies_access(@book, @libraries)
  end

  def update
    @book = Book.find(params[:id])
    @libraries = @book.libraries
    @copies = Copy.copies_access(@book, @libraries)

    if @book.update_attributes(book_params)
      redirect_to books_url(@book)
    else
      render "edit"
    end
  end

  def is_admin?
    if current_user.admin != true
      redirect_to books_url, notice: "You do not have permissions to do that!"
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :genre, :subgenre, :pages, :publisher)
  end

end

app/controllers/borrows_controller.rb
class BorrowsController < ApplicationController
  before_action :authenticate_user!


  def create
    @borrow = Borrow.new
    @borrow.due_date = Time.now + 1.week
    @borrow.user = current_user
    @book = Book.find(params[:book_id])
    @borrow.book = @book
    @library = Library.find(params[:library_id])
    @borrow.library = @library
    # checks to see if all are loaned
    if Borrow.book_available?(@book, @library)
      @borrow.save
      redirect_to user_url(current_user), notice: "Book added!"
    else
      redirect_to request.referrer, notice: "All copies have been loaned, please check back later!"
    end
  end

  def update
    # Nested route gives a book id for the params, need to figure out how to get params to list borrow_id instead
    # Probably an association problem
    @borrow = Borrow.find(params[:book_id])
    @borrow.update(borrow_status: "returned")
    @borrow.update(date_returned: Time.now)

    @notifications = @borrow.book.notifications.unsent_notifications
    Notification.notification_mailer(@notifications)
    redirect_to user_url(current_user), notice: "Book Returned!"
  end

end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController

  def show
    @library = Library.find(params[:id])
    @books = @library.books
  end

end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController

  def show
    @user = User.find(params[:id])
    @on_loan = @user.borrows.on_loan
    @returned = @user.borrows.returns
    @notifications = @user.notifications.unsent_notifications
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/borrows_helper.rb
module BorrowsHelper
end

app/helpers/copies_helper.rb
module CopiesHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BestLibrary</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">

        <header>
          <h1><%= link_to "Best Libraries 2018", books_path %></h1>
          <% if user_signed_in? %>
            <h6>Currently signed in as: <%= current_user.email %></h6>
          <% end %>
          <div class="float-right">
            <%= form_tag books_path, :method => 'get' do %>
              <p>
                <%= text_field_tag :search, params[:search] %>
                <%= submit_tag "Search", :name => nil, :class => "btn btn-primary"%>
              </p>
            <% end %>
          </div>
          <nav>
            <ul class="nav">
              <% if user_signed_in? %>
                <li class="nav-item"><%= link_to "My Profile", current_user, :class => "nav-link" %></li>
                <li class="nav-item"><%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :class => "nav-link"  %></li>
                <% if current_user.admin == true %>
                    <li class="nav-item"><%= link_to "Add A Book", new_book_path, :class => "nav-link" %></li>
                    <li class="nav-item"><%= link_to "Admin Panel", rails_admin_path, :class => "nav-link" %></li>
                <% end %>
              <% else %>
                <li class="nav-item"><%= link_to "Register", new_user_registration_path, :class => "nav-link" %></li>
                <li class="nav-item"><%= link_to "Login", new_user_session_path, :class => "nav-link"%></li>
              <% end %>
            </ul>
          </nav>
        </header>

        <main>

            <% if flash && flash.any?  %>
              <% flash.each do |key, message| %>
                <h4><% key %></h4>
                <% if message && message.class != String && message.any?  %>
                  <% message.each do |sub_message|  %>
                  <div class="alert alert-primary">
                    <h5><%= sub_message %></h5>
                  </div>
                <% end %>
                <% else %>
                  <div class="alert alert-primary">
                    <h5><%= message %></h5>
                  </div>
                <% end  %>
              <% end %>
            <% end %>
            <%= yield %>
        </main>

    </div>
  </body>
</html>